server:
  port: 10004

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-front
  redis:
    host: localhost
    port: 6379
    password:

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800000 #注意这个是毫秒数 目前是7天
  tokenHead: Bearer
csmall:
  jwt:
    expiration: 640800
    secret: mySecret


mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    cn.tedu.mall: debug