server:
  port: 10004

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-front

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl