my:
  server:
    addr: localhost
spring:
  jackson:
    default-property-inclusion: always
  datasource:
    user:
      jdbc-url: jdbc:mysql://${my.server.addr}:3306/mall_ums?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: ${my.server.addr}
    port: 6379
    password:

logging:
  level:
    cn.tedu.mall: trace