spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: always
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    password:

dubbo:
  application:
    name: mall-seckill
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
    use-as-metadata-center: false
    use-as-config-center: false
  consumer:
    check: false
  cloud:
    subscribed-services:
logging:
  level:
    cn.tedu.mall: trace