spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_oms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-order
  jackson:
    # 为null的属性不显示到响应结果中
    default-property-inclusion: always
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    port: 6379
    host: 192.168.137.150
    password:
dubbo:
  application:
    name: mall-order
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false
  cloud:
    subscribed-services: mall-front
logging:
  level:
    cn.tedu.mall: trace
rocketmq:
  name-server: 192.168.137.150:9876
  producer:
    group: order-producer-group
  consumer:
    group: order-consumer-group